### ISSUE TITLE
`positioned over` is invalid

### ISSUE THREAD

**Issue by RevolvingMadness** [SpyglassMC/Spyglass#1028]
When I use the command `execute positioned over` it gives me an error. But in-game it works fine! This isn't a real big issue, so it's a easy fix.

**Comment by MulverineX** [comment]
What's the full command you used?

**Comment by RevolvingMadness** [comment]
`execute as @a at @s positioned over world_surface if entity @s[dy=999] run say you are under the sun.`

**Comment by MulverineX** [comment]
I just tested this and it is working. I think your problem is that you're using the wrong Cmd version. Please check in extension settings that you have this set to 1.19.4.
![image](https://user-images.githubusercontent.com/12068027/225087995-799770a0-22b8-4d21-b374-3ccfe2e44fed.png)
@RevolvingMadness
