### ISSUE TITLE
Add a warning for a common macro mistake

### ISSUE THREAD

**Issue by MulverineX** [SpyglassMC/Spyglass#1114]
Example A:
```hs
$execute as @s at @s align xyz run summon minecraft:block_display ~.5 ~.5 ~.5 {block_state:{Name:"minecraft:${block}"}}
```
As someone who has worked with JavaScript and other languages quite a lot, this is a familiar mistake. Essentially, we should detect this common pattern and provide the user with a "did you actually mean to do that?" sort of error.

```regex
/\$\{[\w:\-]+\}/
```

**Comment by SPGoding** [comment]
Instead of checking for `${}` explicitly, how about checking for the lack of `$()` (which generalizes this warning to macros that don't reference macro parameters)? In the case where there are mixed `${}` and `$()`, the highlighting difference between them should (?) be enough to draw the user's attention to them.

**Comment by MulverineX** [comment]
Yeah that would be fine, especially once we have a impdoc mechanism for macros, the user won't get autocomplete, and that'll probably help prevent it too
