### ISSUE TITLE
Macro syntax highlighting

### ISSUE THREAD

**Issue by Calverin** [SpyglassMC/Spyglass#1122]
Support basic highlighting and error checking

**Comment by Kesuaheli** [comment]
How would that be realisticly possible? Because a macro can contain spaces, you can not know how many arguments will be added at runtime.
One option would be to assume every macro adds one argument without spaces. But if someone than wants to add a multi-argument macro, they would most likely get errors.
Even then, there're weird cases where nobody knows what the command looks like at runtime.
```
$execute as @e[nbt!=$(foo)] lol I am an error $(bar) run say Hello World!
```
I don't know why someone would ever do this. (One can argue that it's probably right to mark this as wrong, lol)
But it will run fine if you pass in `{"foo": "{CustomName:\"", "bar": "\"}]"}`

The only way that I can think of which will work is to use some mcdoc syntax to specify which type/s this macro can have. (Whould be soo cool!)
But I think that's not what you had in mind.

**Comment by Calverin** [comment]
The current plan is to keep things very simple, by highlighting macro lines a different color (already done), but keeping macro entries, e.g. "$(foo)" highlighted differently, and marking the command as an error if it's a macro command with none of those entries. If it's a $$ command it'll probably just be highlighted differently and ignore all error checking because there's not much you can do there

**Comment by Kesuaheli** [comment]
Ah I see
