### ISSUE TITLE
Completing NBT values inserts a duplicate end quote

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1280]
Example: 
```
execute if predicate {condition:""}
```
When autocompleting inside the quotes, it results in this:
```
execute if predicate {condition:"all_of""}
```

**Comment by misode** [comment]
Disabling the `insertReplaceSupport` capability fixes this *(but at what cost?)*

Also strange that this works fine in JSON files.

**Comment by SPGoding** [comment]
> vscode decides to not use insert mode for JSON strings

This is indeed the case, as the built-in JSON extension contributes a default configuration to use replace mode instead of insert mode

https://github.com/microsoft/vscode/blob/35ac2d01a6b7ae2e0141377a6a924f050aa65237/extensions/json-language-features/package.json#L135

I think we can similarly add a default configuration in `packages/vscode-extension/package.json` to use replace mode for `mcfunction` as well? I can't tell why anyone would prefer the insert mode tbh.
