### ISSUE TITLE
`/say` selector parser is too strict

### ISSUE THREAD

**Issue by misode** [SpyglassMC/Spyglass#1304]
It shouldn't error for cases like this. Reference the decompiled code to see how Minecraft parses this.

![image](https://github.com/SpyglassMC/Spyglass/assets/17352009/f5e00f9e-a8b5-4593-8c41-9411ea1f46f6)

**Comment by TheAfroOfDoom** [comment]
curious if it just prints the raw selector text if it fails to parse one too. not that this is really that same case

**Comment by Calverin** [comment]
> curious if it just prints the raw selector text if it fails to parse one too. not that this is really that same case

Tested, if the selector has an open square bracket to start parameters it does full error checking and the command will fail if it's not closed or if there are errors. Otherwise if it's an invalid selector it doesn't care about it and treats it as normal text. If it's a valid selector and doesn't find any entities it just skips the selector.
