### ISSUE TITLE
@s not suggesting non-mob NBT paths

### ISSUE THREAD

**Issue by tryashtar** [SpyglassMC/Spyglass#1440]
In this command
```mcfunction
data get entity @s Pickup
```
the key I'm looking for is `PickupDelay`, from item entities, but the suggestion doesn't appear.

![image](https://github.com/SpyglassMC/Spyglass/assets/26075577/8365189a-e35e-4e65-aa30-d1280c37e24a)

If you do `@e[type=item,limit=1]` instead, it works ok.

Extension version: `v4.0.0`
Pack format: `48`

**Comment by misode** [comment]
I suddenly can't reproduce anymore (I could when you created this issue). Can you still reproduce @tryashtar?

**Comment by misode** [comment]
I'm going to blame this on https://github.com/SpyglassMC/vanilla-mcdoc/commit/89c6b84fff9e7744d1e2e609fc57f57d739a731a, which I coincidentally [reverted 3 minutes after you created this report](https://github.com/SpyglassMC/vanilla-mcdoc/commit/e935c781822212ab621c7a504a9635a116f52b79) because of [your other issue](https://github.com/SpyglassMC/Spyglass/issues/1439), I did not know these two were related

**Comment by tryashtar** [comment]
Yes, seems fixed in 4.0.1 for me too!
