### ISSUE TITLE
area_effect_cloud nbt Particle.<stuff> missing possible keys

### ISSUE THREAD

**Issue by RoarkCats** [SpyglassMC/Spyglass#1573]
`area_effect_cloud` entities have some nbt `Particle.item` which isn't currently recognized (Unkown key)

`Particle.type` is, however, nothing else is

I know that `Particle.item` and `Particle.block_state` are missing, but there may be more as some particles have extra data

![image](https://github.com/user-attachments/assets/c1af4323-3668-4953-9a19-9ccc86a6c51a)

**Comment by misode** [comment]
I did a bit of analysis on this. It's not immediately clear how to fix this properly in the mcdoc runtime checker since it doesn't support spreading the union of all particle types.

I have fixed this in vanilla-mcdoc by adding a `any` fallback when there is no `type` context, that should at least get rid of the error. https://github.com/SpyglassMC/vanilla-mcdoc/commit/e1a6ccee9cba1ce981fe063b9ae59d79b3bf504b
