### ISSUE TITLE
Cannot change Spyglass loaded version and key "tag" is unknown

### ISSUE THREAD

**Issue by ChainDev162** [SpyglassMC/Spyglass#1577]
Hello, I was making a modpack for my world which is on 1.20.6, and I tried to change the loaded Spyglass version to 1.20.6, it kept bugging me with this error message:
![image](https://github.com/user-attachments/assets/976e986e-6d3d-4d87-ae78-200518ad6a46)
When I tried to change it using `.spyglassrc.json` to 1.20.6, it said this when i hovered over `execute`:
![image](https://github.com/user-attachments/assets/30f400d5-94fb-48b5-b14d-75e2b77edc42)
![image](https://github.com/user-attachments/assets/5c37270a-60dd-4ffe-9cd2-3f0b7a36b593)
![image](https://github.com/user-attachments/assets/489caaae-0e69-4ff5-b08a-364d0e71f118)
I reloaded it not once, not twice, but three times so far, and i tried using `spyglass.json`, nothing.
Please help as I'm just trying to have fun as a beginner to minecraft technicality.
```[tasklist]
### Tasks
- [ ] Fix version changing
- [ ] Fix weird bug with `execute`
```

**Comment by ChainDev162** [comment]
For anyone wondering, the command which has the weird `execute` message was `execute as @a[nbt={SelectedItem:{id:"minecraft:sugar",tag:{display:{Name:"{\"text\":\"Crack\"}"}}}}] at @s run function crack:apply_effects`, also here's my file structure:
![image](https://github.com/user-attachments/assets/666adaab-23d1-4baa-b913-8699dcba9620)

**Comment by Ellivers** [comment]
The Spyglass config file needs to be at the root of your workspace, meaning at the same level as your python file there. Also, the pack format for 1.20.6 is 41, as can be seen [here](https://minecraft.wiki/w/Pack_format#List_of_data_pack_formats).

**Comment by misode** [comment]
Adding to what Ellivers said, even in 1.20.6 your command would not be valid anymore. The `tag` field no longer exists. Instead you should probably use `execute if items`.

**Comment by Ellivers** [comment]
Additionally, the `tag` warning will still show in 1.20.6, since it was removed in 1.20.5. You need to use the `components` tag or `execute if items` command to select based on item data. For more information and help regarding that, I'd recommend joining the [Minecraft Commands discord server](https://discord.gg/QAFXFtZ).

**Comment by ChainDev162** [comment]
> As Misode pointed out, the `tag` warning will still show in 1.20.6, since it was removed in 1.20.5. You need to use the `components` tag or `execute if items` command to select based on item data. For more information and help regarding that, I'd recommend joining the [Minecraft Commands discord server](https://discord.gg/QAFXFtZ).

so this?
`execute as @a if data entity @s {SelectedItem:{id:"minecraft:sugar",display:{Name:'{"text":"Crack"}'}}} run function crack:apply_effects`

**Comment by Ellivers** [comment]
With `execute if items`, the command would be `execute as @a if items entity @s weapon.mainhand minecraft:sugar[minecraft:custom_name='{"text":"Crack"}'] run function crack:apply_effects`.
However, for most cases, I wouldn't recommend checking for the name of the item. It depends on your use case, but most of the time it's a better idea to give it a tag within the `minecraft:custom_data` component and check for that instead, since text components can be unreliable. This isn't really a place for command help, so if you have more questions, please join the Discord server I linked.
