### ISSUE TITLE
Invalid version detected

### ISSUE THREAD

**Issue by zahadneokurkycz** [SpyglassMC/Spyglass#1632]
![Image](https://github.com/user-attachments/assets/bf4b60b3-bec5-437b-b048-6ea79cb114ce)
I tried to reload spyglass like 10+ times but nothing worked. I am currently running minecraft version 1.20.4

It always detects every datapack as for version 1.21.1
And because of that I get a lots of false errors.
![Image](https://github.com/user-attachments/assets/e145d8f1-e0fe-4d78-9886-2b4c404bfce5)

**Comment by misode** [comment]
Could you run the `Spyglass: Show Output` command and share that log here?

**Comment by Kesuaheli** [comment]
1. Do you have a (Spyglass config file](https://spyglassmc.com/user/config.html) (`spyglass.json` or `.spyglassrc.json`) in your workspace, that overrides `env.gameVersion` with `"1.21.1"`?
  - You have to change or remove this config option. As it will always be used instead of the auto detected pack_format of your `pack.mcmeta`.

2. Do you have multiple data packs in your workspace folder? Does one of them contain a `pack_format` of `48`?
  - Spyglass (currently) only allows a single loaded version. Make sure they are all on the same version, as spyglass takes the first it could find.
  - If that isn't an option, see 3.

3. Do you have a resource pack in your workspace? Or any other `pack.mcmeta` file, that sets another `pack_format`?
  - Unfortunately, Spyglass can't recognize the difference between a `pack.mcmeta` that belongs to a data pack, and any other `pack.mcmeta` (e.g. one from a resourcepack, or one you just created just for fun, lol)
  - In the likely case you want to keep both packs in your workspace, you can create a (Spyglass config file](https://spyglassmc.com/user/config.html) (`spyglass.json` or `.spyglassrc.json`) in your workspace folder with the following content:
```json
{
	"env": {
		"gameVersion": "1.20.4"
	}
}
```

**Comment by zahadneokurkycz** [comment]
> 1. Do you have a (Spyglass config file](https://spyglassmc.com/user/config.html) (`spyglass.json` or `.spyglassrc.json`) in your workspace, that overrides `env.gameVersion` with `"1.21.1"`?
> 
> * You have to change or remove this config option. As it will always be used instead of the auto detected pack_format of your `pack.mcmeta`.
> 
> 2. Do you have multiple data packs in your workspace folder? Does one of them contain a `pack_format` of `48`?
> 
> * Spyglass (currently) only allows a single loaded version. Make sure they are all on the same version, as spyglass takes the first it could find.
> * If that isn't an option, see 3.
> 
> 3. Do you have a resource pack in your workspace? Or any other `pack.mcmeta` file, that sets another `pack_format`?
> 
> * Unfortunately, Spyglass can't recognize the difference between a `pack.mcmeta` that belongs to a data pack, and any other `pack.mcmeta` (e.g. one from a resourcepack, or one you just created just for fun, lol)
> * In the likely case you want to keep both packs in your workspace, you can create a (Spyglass config file](https://spyglassmc.com/user/config.html) (`spyglass.json` or `.spyglassrc.json`) in your workspace folder with the following content:
> 
> {
> 	"env": {
> 		"gameVersion": "1.20.4"
> 	}
> }

Thanks for help! I had multiple packs in one folder and one of them did in fact had format 48. I tried to resolve it with spyglass config file but that didn't help. So, after opened just one datapack, then it detected the version correctly.
