### ISSUE TITLE
Failed biome tags

### ISSUE THREAD

**Issue by JustFoxx** [SpyglassMC/Spyglass#930]
Introduced in 1.18.2 locatebiome tags, doesn't work in extension, it says about  `Failed to resolve namespaced ID “minecraft:is_forest” in cache category “tag/worldgen/biome”`
![Zrzut ekranu_wybierz obszar_20220326131420](https://user-images.githubusercontent.com/73485099/160238950-5db818a1-8c40-4925-b79c-aafbbb1d318c.png)

**Comment by SPGoding** [comment]
The problem here is that [SPGoding/vanilla-datapck](https://github.com/SPGoding/vanilla-datapck) stopped updating in favor of [misode/mcmeta](https://github.com/misode/mcmeta), but the v3 version of the language server hasn't been migrated to use mcmeta yet. I personally don't really want to update it though as v4 is getting closer to finish and worldgen support isn't a top priority at the moment. Sorry for any incovenience.
